"""Scaffolds complete static websites on request."""
from __future__ import annotations

import json
from pathlib import Path

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{ --bg:#0e1420; --panel:#161f2f; --acc:{accent}; --text:#e6edf5; }}
  * {{ margin:0; box-sizing:border-box; }}
  body {{ background:var(--bg); color:var(--text); font-family:'Segoe UI',system-ui,sans-serif; }}
  header {{ padding:70px 20px 50px; text-align:center;
           background:linear-gradient(160deg,var(--panel),var(--bg)); }}
  h1 {{ font-size:2.4rem; letter-spacing:1px; }}
  .accent {{ color:var(--accent, var(--acc)); }}
  header p {{ color:#9db0c6; margin-top:12px; font-size:1.05rem; }}
  nav {{ display:flex; gap:14px; justify-content:center; margin-top:26px; flex-wrap:wrap; }}
  nav a {{ color:var(--text); text-decoration:none; border:1px solid #2b3b55; padding:9px 22px;
          border-radius:24px; transition:.2s; }}
  nav a:hover {{ border-color:var(--acc); color:var(--acc); }}
  section {{ max-width:900px; margin:40px auto; padding:0 20px; }}
  .cards {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(240px,1fr)); gap:16px; }}
  .card {{ background:var(--panel); border-radius:12px; padding:22px; }}
  .card h3 {{ color:var(--acc); margin-bottom:8px; }}
  footer {{ text-align:center; color:#71809a; padding:30px; font-size:.85rem; }}
</style>
</head>
<body>
<header>
  <h1>{title}</h1>
  <p>{tagline}</p>
  <nav>{nav}</nav>
</header>
<section><div class="cards">{sections}</div></section>
<footer>© {year} {title} — built by Ziggler</footer>
</body>
</html>
"""


def scaffold(target_dir: str, spec: dict | None = None) -> bool:
    """Create index.html (+ site.json) from spec {title, tagline, sections[], accent}."""
    spec = spec or {}
    title = spec.get("title", "My Site")
    tagline = spec.get("tagline", "A website generated by Ziggler.")
    accent = spec.get("accent", "#4cc2ff")
    sections = spec.get("sections") or [
        {"heading": "About", "body": f"This is {title}."},
        {"heading": "Contact", "body": "Reach out anytime."},
    ]

    d = Path(target_dir)
    d.mkdir(parents=True, exist_ok=True)
    nav = "".join(f'<a href="#{i}">{s["heading"]}</a>' for i, s in enumerate(sections))
    cards = "".join(
        f'<div class="card" id="{i}"><h3>{s["heading"]}</h3><p>{s["body"]}</p></div>'
        for i, s in enumerate(sections)
    )
    page = INDEX_TEMPLATE.format(
        title=title, tagline=tagline, accent=accent, nav=nav,
        sections=cards, year=__import__("datetime").date.today().year,
    )
    (d / "index.html").write_text(page, encoding="utf-8")
    (d / "site.json").write_text(json.dumps(spec, indent=2), encoding="utf-8")
    return (d / "index.html").exists()
